-- Minimal local reproduction of the inspected schema/RLS, not a migration.
-- Auth helpers simulate signed Supabase JWT claims in isolated tests only.
create role anon;
create role authenticated;
create role service_role bypassrls;
create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create function auth.jwt() returns jsonb language sql stable as $$ select jsonb_build_object('role',current_setting('request.jwt.claim.role',true)) $$;
grant usage on schema auth to anon,authenticated,service_role;
create table public.users(id uuid primary key,type text not null default 'human' check(type in ('human','agent')),name text,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.rooms(id uuid primary key default gen_random_uuid(),name text not null,visibility text not null default 'unlisted' check(visibility in ('public','unlisted')),current_world_version_id uuid,forked_from_room_id uuid references public.rooms(id),forked_at_event_id bigint,created_by uuid references public.users(id),created_at timestamptz not null default now());
create table public.events(id bigint generated by default as identity primary key,room_id uuid not null references public.rooms(id),user_id uuid references public.users(id),type text not null check(type in ('message','participant_joined','participant_left','world_changed')),payload jsonb not null default '{}',created_at timestamptz not null default now());
create table public.world_versions(id uuid primary key default gen_random_uuid(),room_id uuid not null references public.rooms(id),markdown text not null,compiled_through_event_id bigint references public.events(id),previous_version_id uuid references public.world_versions(id),created_at timestamptz not null default now());
alter table public.rooms add constraint rooms_current_world_version_fk foreign key(current_world_version_id) references public.world_versions(id);
alter table public.rooms add constraint rooms_forked_at_event_fk foreign key(forked_at_event_id) references public.events(id);
create table public.mcp_tokens(id uuid primary key default gen_random_uuid(),owner_user_id uuid not null references public.users(id),agent_user_id uuid references public.users(id),token_hash text not null unique,created_at timestamptz not null default now(),revoked_at timestamptz);
-- Signature-only stub: live token creation is inspected, not reimplemented here.
create function public.create_mcp_token(agent_name text default 'Agent') returns table(token text,agent_user_id uuid) language plpgsql as $$ begin raise exception 'Token generation is outside this local fixture'; end $$;
alter table public.users enable row level security;
alter table public.rooms enable row level security;
alter table public.events enable row level security;
alter table public.world_versions enable row level security;
alter table public.mcp_tokens enable row level security;
create policy "users readable" on public.users for select using(true);
create policy "users update self" on public.users for update using(auth.uid()=id) with check(auth.uid()=id);
create policy "rooms readable" on public.rooms for select using(true);
create policy "authenticated create rooms" on public.rooms for insert to authenticated with check(created_by=auth.uid());
create policy "creator updates room" on public.rooms for update to authenticated using(created_by=auth.uid()) with check(created_by=auth.uid());
create policy "events readable" on public.events for select using(true);
create policy "authenticated create events" on public.events for insert to authenticated with check(user_id=auth.uid());
create policy "worlds readable" on public.world_versions for select using(true);
create policy "room creator creates worlds" on public.world_versions for insert to authenticated with check(exists(select 1 from public.rooms r where r.id=world_versions.room_id and r.created_by=auth.uid()));
create policy "own mcp tokens readable" on public.mcp_tokens for select to authenticated using(owner_user_id=auth.uid());
create policy "own mcp tokens insertable" on public.mcp_tokens for insert to authenticated with check(owner_user_id=auth.uid());
create policy "own mcp tokens revocable" on public.mcp_tokens for update to authenticated using(owner_user_id=auth.uid()) with check(owner_user_id=auth.uid());
grant usage on schema public to anon,authenticated,service_role;
grant all on all tables in schema public to anon,authenticated,service_role;
grant usage,select on all sequences in schema public to anon,authenticated,service_role;
